### ISSUE TITLE
Probably misconfigured

### ISSUE THREAD

**Issue by zrothberg** [agawronski/pandas_redshift#20]
### Actual Behaviour
I assume I either am not using this correctly or have misconfigured redshift. 

this is my code

```
pr.connect_to_redshift(dbname = "shopifydtc",
                        host = "beautybakerie.capqpzprxn1m.us-west-1.redshift.amazonaws.com",
                        port = "5439",
                        user = "*******",
                        password = "**********")
```

I get this error

```
Traceback (most recent call last):
  File "/Users/zacharyrothberg/PycharmProjects/awsplug/connector.py", line 20, in <module>
    password = "**********")
  File "/Users/zacharyrothberg/PycharmProjects/awsplug/venv/lib/python3.6/site-packages/pandas_redshift/core.py", line 18, in connect_to_redshift
    **kwargs)
  File "/Users/zacharyrothberg/PycharmProjects/awsplug/venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Operation timed out
	Is the server running on host "beautybakerie.capqpzprxn1m.us-west-1.redshift.amazonaws.com" (54.219.190.55) and accepting
	TCP/IP connections on port 5439?

```

This is my configuration 
```
PortPort number on which the database accepts connections. | 5439
-- | --
Publicly AccessibleWhether the cluster has a public IP address that can be accessed from the public internet. | Yes
Database NameThe name of the database on this cluster. | shopifydtc
Master UsernameMaster database user. Login with this user name and your Master Username Password specified either when the cluster was launched or when the cluster was modified. | ********
EncryptedWhether data stored on the cluster is encrypted | Yes
KMS Key IDKMS Key ID used to encrypt the database | ***************
JDBC URLURL to connect to the cluster database with a JDBC client. | jdbc:redshift://beautybakerie.capqpzprxn1m.us-west-1.redshift.amazonaws.com:5439/shopifydtc
ODBC URLURL to connect to the cluster database with an ODBC client. Note that you must replace the password with the Master User Password. | Driver={Amazon Redshift (x64)}; Server=beautybakerie.capqpzprxn1m.us-west-1.redshift.amazonaws.com; Database=shopifydtc; UID=********; PWD=insert_your_master_user_password_here; Port=5439
```

Please tell me I'm just doing something dumb

**Comment by zrothberg** [comment]
FIgured it out sorry for the issue being raised.

**Comment by PabTorre** [comment]
@zrothberg  how did you solve it? is it something we can improve on the documentation?

**Comment by zrothberg** [comment]
@PabTorre I just didn't whitelist the ip address(im just learning aws so most issues are because of that) but it worked fine. The only issue I had with the program (i'm writing some code to fix it) is that assigning types was just too hard if you have a bunch of columns and it's not ideal that it can break if you move the order around. I was gonna write some code to take advantage of dictionaries being ordered. To generate a softdict of types from the dataframe keys and allow you to replace the ones you wish to change. Then generate a the list from the completed version.

**Comment by agawronski** [comment]
@zrothberg ... thanks for explaining the problem/solution as you never know when it may help someone else.
